### ISSUE TITLE
Incorrect chromosome size?

### ISSUE THREAD

**Issue by Eve0028** [Evolutionary-Computation-PK/classical-genetic-algorithm#18]
https://github.com/Evolutionary-Computation-PK/classical-genetic-algorithm/blob/a927a892fed4684069d3f10cddcaaa8af0564cd5/source/crossover/point_crossover.py#L16-L31

https://github.com/Evolutionary-Computation-PK/classical-genetic-algorithm/blob/a927a892fed4684069d3f10cddcaaa8af0564cd5/source/crossover/point_crossover.py#L18

Czy tutaj nie miało być:
`chromosome_size = population[0].number_of_genes`?

**Comment by zannna** [comment]
święta racja
